#!/bin/bash
# Скрипт для быстрой настройки проекта для Render

echo "========================================="
echo "Freelancehunt Bot - Render Setup"
echo "========================================="
echo ""
echo "Следующие шаги:"
echo ""
echo "1. Создайте репозиторий на GitHub:"
echo "   https://github.com/new"
echo ""
echo "2. Инициализируйте Git (если еще не сделано):"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit'"
echo "   git branch -M main"
echo "   git remote add origin YOUR_GITHUB_REPO_URL"
echo "   git push -u origin main"
echo ""
echo "3. Перейдите на Render Dashboard и создайте Web Service:"
echo "   https://dashboard.render.com"
echo ""
echo "4. Используйте следующие настройки:"
echo "   - Runtime: Docker"
echo "   - Build Command: (оставить пустым)"
echo "   - Start Command: (оставить пустым)"
echo "   - Plan: Starter"
echo ""
echo "5. Добавьте переменные окружения:"
echo "   TELEGRAM_BOT_TOKEN=ваш_токен"
echo "   HEADLESS_BROWSER=true"
echo "   BROWSER_TYPE=edge"
echo "   DATABASE_FILE=/app/data/freelancehunt_bot.db"
echo "   COOKIES_FILE=/app/data/cookies.json"
echo ""
echo "6. Добавьте Persistent Disk:"
echo "   - Name: bot-data"
echo "   - Mount Path: /app/data"
echo "   - Size: 1 GB"
echo ""
echo "Смотрите DEPLOY.md для подробных инструкций."

