#!/bin/bash
# Скрипт для загрузки cookies на Render сервер

echo "========================================="
echo "Загрузка cookies на Render сервер"
echo "========================================="
echo ""
echo "Способ 1: Через Render Shell (рекомендуется)"
echo ""
echo "1. Откройте Render Dashboard:"
echo "   https://dashboard.render.com/web/srv-d5crfrtactks73csled0"
echo ""
echo "2. Нажмите на 'Shell' в левом меню"
echo ""
echo "3. Выполните команды:"
echo "   cd /app/data"
echo "   nano cookies.json"
echo ""
echo "4. Вставьте содержимое вашего локального cookies.json"
echo "   (Ctrl+Shift+V для вставки в nano)"
echo ""
echo "5. Сохраните: Ctrl+O, Enter, Ctrl+X"
echo ""
echo "Способ 2: Через SSH"
echo ""
echo "1. Подключитесь через SSH:"
echo "   ssh srv-d5crfrtactks73csled0@ssh.oregon.render.com"
echo ""
echo "2. Создайте файл cookies.json в /app/data"
echo ""
echo "========================================="
echo "Важно:"
echo "- Файл cookies.json должен быть в /app/data/"
echo "- После загрузки перезапустите сервис в Dashboard"
echo "========================================="

